---

- include: installation.yml
  when: mode == "install"

- name: collecte des images à supprimer
  shell: "docker images | grep -v -e REPOSITORY | /usr/bin/php {{ pathphpscript_cleanupdocker }}"
  register: dockerimg2delete
  changed_when: false

- name: suppression des images
  shell: "docker rmi {{ item }}"
  failed_when: false
  with_items: "{{ dockerimg2delete.stdout_lines }}"
  when: dockerimg2delete.stdout | trim != ''

- include: nettoyage.yml
  when: mode == "clean"